version: '3.8'

services:
  expo-app:
    build: .
    container_name: expo-mobile
    ports:
      - "19000:19000"
      - "19001:19001"
      - "19002:19002"
    volumes:
      - .:/app
    command: npx expo start --tunnel
